# PostgreSQL Client Authentication Configuration File

# Tipo de conexão:
# - local: socket Unix
# - host: TCP/IP socket

# Permite conexões locais via socket Unix sem senha (trust)
local   all             all                                     trust

# Permite conexões TCP locais (IPv4 e IPv6) com senha md5
host    all             all             127.0.0.1/32            md5
host    all             all             ::1/128                 md5

# Permite conexões de replicação locais
local   replication     all                                     trust
host    replication     all             127.0.0.1/32            trust
host    replication     all             ::1/128                 trust

# Permite conexões TCP de qualquer IP com senha md5
host    all             all             0.0.0.0/0               md5
host    all             all             192.168.18.15/32        md5